version: "3.8"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: "uvicorn devart_lead_api.asgi:application --loop asyncio --host 0.0.0.0"
    #command: "ls -l"
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=tyke.db.elephantsql.com
      - POSTGRES_NAME=pdkwnhnf
      - POSTGRES_USER=pdkwnhnf
      - POSTGRES_PASSWORD=JXhP2vfdJpkV7TZ8B4-icZQ83o0B2zJw
    depends_on:
      - db
