# Generated by Django 4.0 on 2022-01-18 11:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Key Identifier')),
                ('api_key', models.CharField(max_length=511, unique=True, verbose_name='API Key')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('source', models.ForeignKey(on_delete=api.models.Source, to='api.source')),
            ],
        ),
    ]
