# Generated by Django 4.0 on 2022-01-23 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_source_active_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Recieved at')),
                ('ip', models.CharField(max_length=255, verbose_name='Adresa IP')),
                ('headers', models.TextField(verbose_name='Headers')),
                ('data', models.TextField(verbose_name='Data')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
