# Generated by Django 4.0 on 2022-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lead_is_owner_alter_lead_rodne_cislo'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
