# Generated by Django 4.0 on 2022-02-02 18:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_lead_duplicity_lead_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodne_cislo', models.CharField(max_length=20, unique=True, verbose_name='Rodne Cislo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Price')),
                ('bought', models.BooleanField(default=False, verbose_name='Bought')),
                ('created_at', models.DateTimeField(editable=False)),
                ('source', models.ForeignKey(on_delete=api.models.Source, to='api.source')),
            ],
        ),
    ]
