# Generated by Django 4.0 on 2022-02-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rodne_cislo',
            field=models.CharField(max_length=20, verbose_name='Rodne Cislo'),
        ),
    ]
