# Generated by Django 4.0 on 2022-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_offer_rodne_cislo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='addr_city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='lead',
            name='addr_street',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='lead',
            name='addr_zip',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ZIP'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='income',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Requested amount'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='lead',
            name='requested_amount',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Requested amount'),
        ),
    ]
