# Generated by Django 4.0 on 2022-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lead_addr_city_lead_addr_street_lead_addr_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='income',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Income'),
        ),
    ]
