# Generated by Django 4.0 on 2022-02-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_lead_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodne_cislo', models.CharField(max_length=20, unique=True, verbose_name='Rodne Cislo')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Phone number')),
                ('requested_amount', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Requested amount')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-mail')),
                ('income', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Income')),
                ('addr_street', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Street')),
                ('addr_city', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='City')),
                ('addr_zip', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ZIP')),
            ],
        ),
    ]
